system:
  debug:
    log_level: debug
ai:
  provider: "openai" # "openai" or "vertexai"
  openai:
    model: "gpt-3.5-turbo" # Check the list of available models by curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"
  vertexai:
    project: "<YOUR_PROJECT_ID>"
    location: "asia-northeast1"
    model: "gemini-1.5-flash-001"
  commands:
    - describe:
        description: "Generate a detailed description of the Issue."
        parameters:
            language:
                description: "The language for the output (e.g., en, ja)."
                type: string
                required: true
        system_prompt: |
            The following is the GitHub Issue and comments on it. 
            Please generate a detailed description in the specified language: {language}. 
            If the language is not specified or recognized, default to English.\n
    - suggest:
        description: "Provide suggestions for improvement based on the contents of the Issue."
        parameters:
            language:
                description: "The language for the output (e.g., en, ja)."
                type: string
                required: true
        system_prompt: |
            The following is the GitHub Issue and comments on it. 
            Please identify the issues that need to be resolved and provide three suggestions for improvement in the specified language: {language}. 
            If the language is not specified or recognized, default to English.\n
    - ask:
        description: "Answer free-text questions."
        parameters:
            language:
                description: "The language for the output (e.g., en, ja)."
                type: string
                required: true
        system_prompt: |
            The following is the GitHub Issue and comments on it. 
            Based on the content, provide a detailed response to the following question in the specified language: {language}. 
            If the language is not specified or recognized, default to English.\n
