system:
  debug:
    log_level: debug
ai:
  provider: "openai" # "openai" or "vertexai"
  openai:
    model: "gpt-3.5-turbo" # Check the list of available models by curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"
  vertexai:
    project: "<YOUR_PROJECT_ID>"
    location: "asia-northeast1"
    model: "gemini-1.5-flash-001"
  commands:
    - describe:
        description: "Issueの詳細な説明を生成します。"
        system_prompt: "以下はGitHubのIssueとそのコメントです。これに基づいて、詳細な説明を生成してください。\n"
    - suggest:
        description: "Issueの内容に基づいて改善の提案を行います。"
        system_prompt: "以下はGitHubのIssueとそのコメントです。この内容に基づき、解決が必要な問題を特定し、改善の提案を3つ挙げてください。\n"
    - ask:
        description: "自由形式の質問に回答します。"
        system_prompt: "以下はGitHubのIssueとそのコメントです。この内容に基づき、次の質問に対する詳細な回答をしてください:\n"
